import fs from "node:fs/promises";
import path from "node:path";
import type {
  CameraUiCameraRecord,
  CameraUiStore,
} from "./cameraui-types.js";

const CONFIG_PATH = "/data/cameraui-config.json";
const FALLBACK_CONFIG_PATH = "./cameraui-config.json";

/** Routes generated by older bridge releases, rather than returned by Camera.UI. */
export function isLegacyBridgeStreamUrl(url?: string): boolean {
  if (!url) return false;
  // Old bridge-local aliases are obsolete; configured HA/go2rtc RTSP routes
  // remain valid and must survive Camera.UI discovery snapshots.
  return /^rtsps?:\/\/(?:127\.0\.0\.1|localhost):2101\/cui_/i.test(url);
}

export function repairCameraRecord(cam: CameraUiCameraRecord): {
  cam: CameraUiCameraRecord;
  modified: boolean;
} {
  let modified = false;

  // C402 and C120 use Home Assistant's stream resolver, while retaining their saved HAP
  // identity and URL. Do not synthesize sensors or rewrite them to a Camera.UI URL.
  if (/(?:tapo[-_ ]?c402|tapo[-_ ]?c120|tapo[-_ ]?spot)/i.test(`${cam.id} ${cam.name || ""} ${cam.rtspUrl || ""}`)) {
    if (cam.sourceProvider !== "home_assistant") {
      cam.sourceProvider = "home_assistant";
      modified = true;
    }
  }

  // Remove only URL fragments, which are not part of RTSP/HTTP stream identity.
  for (const key of ["rtspUrl", "subRtspUrl", "snapshotUrl"] as const) {
    const value = cam[key];
    if (value?.includes("#")) {
      cam[key] = value.slice(0, value.indexOf("#"));
      modified = true;
    }
  }
  return { cam, modified };
}

export class CameraUiStorage {
  private static cachedStore: CameraUiStore | null = null;

  public static getCachedStore(): CameraUiStore | null {
    return this.cachedStore;
  }

  public static getDefaultStore(): CameraUiStore {
    return {
      config: {
        enabled: true,
        serverUrl: "http://127.0.0.1:8181",
        username: "",
        password: "",
        rtspUsername: "",
        rtspPassword: "",
        mqttEnabled: true,
        mqttTopicPrefix: "camera.ui",
        allowSelfSignedCertificate: true,
        pollIntervalSeconds: 300,
        connectionStatus: "connected",
      },
      // An empty install must stay empty until Camera.UI discovery succeeds.
      // Never synthesize cameras: their persisted HAP identity belongs to the
      // user's actual Camera.UI records.
      cameras: [],
    };
  }

  private static async getFilePath(): Promise<string> {
    try {
      await fs.access("/data");
      return CONFIG_PATH;
    } catch {
      return FALLBACK_CONFIG_PATH;
    }
  }

  public static async load(): Promise<CameraUiStore> {
    if (this.cachedStore) return this.cachedStore;

    const target = await this.getFilePath();
    try {
      const raw = await fs.readFile(target, "utf8");
      const parsed = JSON.parse(raw);
      let hadMigration = false;
      let cameras = Array.isArray(parsed.cameras)
        ? parsed.cameras.map((cam: CameraUiCameraRecord) => {
            const result = repairCameraRecord(cam);
            if (result.modified) hadMigration = true;
            return result.cam;
          })
        : [];

      const storeConfig = {
        ...this.getDefaultStore().config,
        ...(parsed.config || {}),
      };
      storeConfig.enabled = true;
      this.cachedStore = {
        config: storeConfig,
        cameras,
      };
      if (hadMigration) {
        void this.save(this.cachedStore);
      }
      return this.cachedStore;
    } catch {
      this.cachedStore = this.getDefaultStore();
      void this.save(this.cachedStore);
      return this.cachedStore;
    }
  }

  public static async save(store: CameraUiStore): Promise<void> {
    this.cachedStore = store;
    const target = await this.getFilePath();
    try {
      await fs.mkdir(path.dirname(target), { recursive: true });
      await fs.writeFile(target, JSON.stringify(store, null, 2), "utf8");
    } catch (err) {
      // Fallback
    }
  }

  public static async mergeDiscoveredCameras(
    discovered: CameraUiCameraRecord[],
  ): Promise<CameraUiStore> {
    const store = await this.load();
    if (discovered.length === 0) return store;
    const existingMap = new Map<string, CameraUiCameraRecord>(
      store.cameras.map((c) => [c.id, c]),
    );

    // Start with persistent records. Discovery is a snapshot of a remote
    // service and can be incomplete while Camera.UI/go2rtc is starting; an
    // incomplete response must never remove an exported or paired camera.
    const merged: CameraUiCameraRecord[] = [...store.cameras];
    for (const rawItem of discovered) {
      const repaired = repairCameraRecord(rawItem).cam;
      const existing = existingMap.get(repaired.id);
      if (existing) {
        const keepPairedStream =
          existing.isPaired === true &&
          Boolean(existing.rtspUrl) &&
          !isLegacyBridgeStreamUrl(existing.rtspUrl);
        const effectiveRtspUrl = keepPairedStream
          ? existing.rtspUrl
          : repaired.rtspUrl ||
            (isLegacyBridgeStreamUrl(existing.rtspUrl)
              ? undefined
              : existing.rtspUrl);
        const effectiveSubRtspUrl = keepPairedStream
          ? existing.subRtspUrl
          : repaired.subRtspUrl ||
            (isLegacyBridgeStreamUrl(existing.subRtspUrl)
              ? undefined
              : existing.subRtspUrl);
        const mergedItem = repairCameraRecord({
          ...repaired,
          // A paired accessory keeps its configured source across routine
          // discovery. The user can change the source explicitly in settings.
          rtspUrl: effectiveRtspUrl,
          subRtspUrl: effectiveSubRtspUrl,
          snapshotUrl: repaired.snapshotUrl || existing.snapshotUrl,
          // Preserve persistent HAP pairing and network settings
          port: existing.port || repaired.port,
          username: existing.username || repaired.username,
          pincode: existing.pincode || repaired.pincode,
          setupId: existing.setupId || repaired.setupId,
          uuid: existing.uuid || repaired.uuid,
          isPaired: existing.isPaired ?? false,
          homeKitEnabled: existing.homeKitEnabled ?? true,
          motionActive: existing.motionActive ?? false,
          lastMotionAt: existing.lastMotionAt,
          doorbellActive: existing.doorbellActive ?? false,
          lastDoorbellAt: existing.lastDoorbellAt,
          // A direct ffprobe result remains authoritative only for the exact
          // RTSP URL it measured. Discovery metadata must not overwrite it.
          videoCodec:
            existing.videoCodecSource === "ffprobe" &&
            existing.codecProbeUrl === effectiveRtspUrl
              ? existing.videoCodec
              : repaired.videoCodec,
          videoCodecSource:
            existing.videoCodecSource === "ffprobe" &&
            existing.codecProbeUrl === effectiveRtspUrl
              ? "ffprobe"
              : repaired.videoCodecSource || "unknown",
          codecProbeUrl:
            existing.videoCodecSource === "ffprobe" &&
            existing.codecProbeUrl === effectiveRtspUrl
              ? existing.codecProbeUrl
              : undefined,
          codecProbedAt:
            existing.videoCodecSource === "ffprobe" &&
            existing.codecProbeUrl === effectiveRtspUrl
              ? existing.codecProbedAt
              : undefined,
          audioCodec:
            existing.videoCodecSource === "ffprobe" &&
            existing.codecProbeUrl === effectiveRtspUrl
              ? existing.audioCodec
              : undefined,
        }).cam;
        const index = merged.findIndex((camera) => camera.id === repaired.id);
        merged[index] = mergedItem;
      } else {
        merged.push(repaired);
      }
    }

    store.cameras = merged;
    store.config.enabled = true;
    store.config.connectionStatus = "connected";
    store.config.lastSyncedAt = new Date().toISOString();
    store.config.lastError = undefined;
    await this.save(store);
    return store;
  }

  public static async updateCamera(
    cameraId: string,
    updater: (cam: CameraUiCameraRecord) => CameraUiCameraRecord,
  ): Promise<CameraUiStore> {
    const store = await this.load();
    const cleanId = cameraId
      .replace(/^camera\.cameraui_/, "")
      .replace(/^camera\./, "")
      .replace(/^cameraui_/, "");
    const idx = store.cameras.findIndex((c) => {
      const cClean = c.id
        .replace(/^camera\.cameraui_/, "")
        .replace(/^camera\./, "")
        .replace(/^cameraui_/, "");
      return (
        cClean === cleanId ||
        c.id === cameraId ||
        `camera.${c.id}` === cameraId ||
        `camera.cameraui_${cClean}` === cameraId ||
        `cameraui_${cleanId}` === c.id
      );
    });
    if (idx !== -1) {
      store.cameras[idx] = updater({ ...store.cameras[idx] });
      await this.save(store);
    }
    return store;
  }

  public static async updateConnectionStatus(
    status: "connected" | "disconnected" | "error",
    error?: string,
  ): Promise<CameraUiStore> {
    const store = await this.load();
    store.config.connectionStatus = status;
    if (error !== undefined) {
      store.config.lastError = error;
    } else if (status === "connected") {
      store.config.lastError = undefined;
    }
    // Only mark cameras online when server is confirmed connected.
    // Do not force cameras offline when server connection is momentarily interrupted,
    // as direct RTSP streams or HomeKit accessories may still be streaming.
    if (status === "connected") {
      store.cameras.forEach((cam) => {
        cam.status = "online";
      });
    }
    await this.save(store);
    return store;
  }
}
