import fs from "node:fs/promises";
import path from "node:path";
import type {
  CameraUiCameraRecord,
  CameraUiConfig,
  CameraUiStore,
} from "./cameraui-types.js";

const CONFIG_PATH = "/data/cameraui-config.json";
const FALLBACK_CONFIG_PATH = "./cameraui-config.json";

/** Routes generated by older bridge releases, rather than returned by Camera.UI. */
export function isLegacyBridgeStreamUrl(url?: string): boolean {
  if (!url) return false;
  // The approved Tapo C402 endpoint uses port 62291 and is intentionally not matched.
  return /^rtsps?:\/\/192\.168\.110\.(?:46|147):8554\//i.test(url) ||
    /^rtsps?:\/\/(?:127\.0\.0\.1|localhost):2101\/cui_/i.test(url);
}

// Camera.UI go2rtc stream names from its exported configuration.  These are
// identifiers, not camera credentials, and replace old bridge-local aliases.
// NOTE: Wyze (cba17b87), EZVIZ Patio Trasero (4661fae4), and Tapo C120 (ec110a11)
// are intentionally EXCLUDED: they already have correct go2rtc routes at
// 192.168.110.147:8554 in DEFAULT_CAMERAS. Including them here would cause
// migrateLegacyBridgeStream to overwrite those routes with rtsp://Admin:***@192.168.110.46:2101/cui_*
// which fails with 401 Unauthorized.
const CANONICAL_CUI_STREAMS: Record<string, string> = {
  "cameraui_c47abc56-42a1-47d5-9c99-fafa2bba5193": "cui_jardin-vimtag_stream_1",
  "cameraui_af880e8a-1ef3-4545-a0c8-9877d8bca4f3": "cui_sala-vimtag_stream_1",
  "cameraui_ffd37848-ae95-403b-87f5-3fff4afe8334": "cui_vimtag_cochera_stream_1",
  "cameraui_25237d2a-48ae-4f77-9cb9-c26608d58128": "cui_vimtag_gym_stream_1",
  "cameraui_c0abed4c-0a46-4331-b480-32aa614973f8": "cui_vimtag_oficina_stream_1",
  "cameraui_5715a9d4-fc49-4417-b477-c3159472ca29": "cui_vimtag_recamara_visita_stream_1",
};

function migrateLegacyBridgeStream(
  cam: CameraUiCameraRecord,
  config: CameraUiConfig,
): CameraUiCameraRecord {
  const streamName = CANONICAL_CUI_STREAMS[cam.id];
  if (!streamName) return cam; // Tapo C402 and unknown cameras stay untouched.

  const desiredUser = (config.rtspUsername || config.username || "Admin").trim();
  const desiredPassword = (config.rtspPassword || config.password || "Anubis2026.").trim();
  const credentials = `${encodeURIComponent(desiredUser)}:${encodeURIComponent(desiredPassword)}@`;

  // Camera.UI may disclose the physical Wyze RTSP address during discovery.
  // That endpoint is not a stable bridge source: it goes unavailable whenever
  // the camera reconnects, while Camera.UI's own `cui_*` restream persists.
  // Prefer the configured Camera.UI listener for every known canonical stream.
  const isCanonical = new RegExp(`:2101/${streamName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}$`, "i").test(cam.rtspUrl || "");
  if (isCanonical) {
    try {
      const url = new URL(cam.rtspUrl!);
      const currentUser = decodeURIComponent(url.username || "");
      const currentPassword = decodeURIComponent(url.password || "");
      if (
        currentUser === desiredUser &&
        (currentPassword === desiredPassword ||
          currentPassword === desiredPassword.replace(/\.$/, "") ||
          `${currentPassword}.` === desiredPassword)
      ) {
        return cam;
      }
      return {
        ...cam,
        rtspUrl: `rtsp://${credentials}${url.hostname}:2101/${streamName}`,
      };
    } catch {
      return cam;
    }
  }

  try {
    let host = "192.168.110.46";
    if (cam.rtspUrl) {
      try {
        const u = new URL(cam.rtspUrl);
        if (u.hostname && u.hostname !== "127.0.0.1" && u.hostname !== "localhost") {
          host = u.hostname;
        }
      } catch {}
    }
    if (config.serverUrl) {
      try {
        const u = new URL(config.serverUrl);
        if (u.hostname && u.hostname !== "127.0.0.1" && u.hostname !== "localhost") {
          host = u.hostname;
        }
      } catch {}
    }
    return { ...cam, rtspUrl: `rtsp://${credentials}${host}:2101/${streamName}` };
  } catch {
    return cam;
  }
}

export function repairCameraRecord(cam: CameraUiCameraRecord): {
  cam: CameraUiCameraRecord;
  modified: boolean;
} {
  let modified = false;

  // The C402 RTSP endpoint is published by the Home Assistant add-on at
  // 192.168.110.147:62291, not by Camera.UI. Keep its existing single UI card
  // and HAP identity, but label its real stream origin accurately.
  if (/tapo-c402/i.test(cam.rtspUrl || "") || /tapo\s*c402/i.test(cam.name || "")) {
    if (cam.sourceProvider !== "home_assistant") {
      cam.sourceProvider = "home_assistant";
      modified = true;
    }
    const knownC402Sensors = [
      {
        id: "binary_sensor.omni_ai_sensors_persona_tapo_c402",
        name: "Omni AI Sensors persona_tapo_C402",
      },
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_tapo_frente_de_calle",
        name: "Omni AI Sensors - Mac MAC - Persona - TAPO-FRENTE DE CALLE",
      },
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_mascota_tapo_frente_de_calle",
        name: "Omni AI Sensors - Mac MAC - Mascota - TAPO-FRENTE DE CALLE",
      },
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_vehiculo_tapo_frente_de_calle",
        name: "Omni AI Sensors - Mac MAC - Vehiculo - TAPO-FRENTE DE CALLE",
      },
      {
        id: "binary_sensor.omni_ai_sensors_vehiculo_tapo_c402",
        name: "Omni AI Sensors vehiculo_tapo_C402",
      },
    ];
    for (const sensor of knownC402Sensors) {
      if (!cam.realEntities?.some((e) => e.id === sensor.id)) {
        cam.realEntities = [
          ...(cam.realEntities || []),
          {
            id: sensor.id,
            domain: "binary_sensor",
            type: "motion",
            name: sensor.name,
            state: false,
            matterExported: false,
          },
        ];
        modified = true;
      }
    }
  }

  // Ensure any camera with audio defaults to AAC audioCodec for zero-transcoding HomeKit passthrough
  if (cam.hasAudio !== false && (!cam.audioCodec || cam.audioCodec === "unknown")) {
    cam.audioCodec = "aac";
    modified = true;
  }

  // Strip trailing hash fragments
  if (cam.rtspUrl && cam.rtspUrl.includes("#")) {
    cam.rtspUrl = cam.rtspUrl.substring(0, cam.rtspUrl.indexOf("#"));
    modified = true;
  }
  if (cam.subRtspUrl && cam.subRtspUrl.includes("#")) {
    cam.subRtspUrl = cam.subRtspUrl.substring(0, cam.subRtspUrl.indexOf("#"));
    modified = true;
  }
  if (cam.snapshotUrl && cam.snapshotUrl.includes("#")) {
    cam.snapshotUrl = cam.snapshotUrl.substring(
      0,
      cam.snapshotUrl.indexOf("#"),
    );
    modified = true;
  }

  /*
   * Camera.UI is the source of truth for RTSP URLs and probed capabilities.
   * Do not infer a camera from its display name or replace its source with a
   * site-specific URL here: doing so breaks newly discovered cameras and can
   * remount an already paired accessory with the wrong stream.
   */
  /* if (name.includes("wyze") || url.includes("wyze") || url.includes("192.168.110.118")) {
    if (cam.rtspUrl && cam.rtspUrl.includes("/stream1")) {
      cam.rtspUrl = cam.rtspUrl.replace("/stream1", "/stream0");
      modified = true;
    }
    const targetUrl = "rtsp://192.168.110.147:8554/wyze_patio_trasero";
    if (cam.rtspUrl !== targetUrl) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
    if (!cam.width || cam.width < 1920) {
      cam.width = 1920;
      cam.height = 1080;
      cam.fps = 30;
      modified = true;
    }
    cam.videoCodec = "h264";
    cam.strategy = "passthrough_h264";
  }
  // Vimtag Gym: 2560x1440 2K HEVC
  else if (url.includes("vimtag_gym") || name.includes("gym")) {
    const targetUrl = "rtsp://192.168.110.147:8554/vimtag_113";
    if (cam.rtspUrl !== targetUrl) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
    cam.width = 2560;
    cam.height = 1440;
    cam.fps = 20;
    cam.videoCodec = "hevc";
    cam.strategy = "passthrough_hevc";
  }
  // Vimtag Cochera: 2560x1440 2K HEVC
  else if (url.includes("cochera") || name.includes("cochera")) {
    const targetUrl = "rtsp://192.168.110.147:8554/cochera";
    if (cam.rtspUrl !== targetUrl) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
    cam.width = 2560;
    cam.height = 1440;
    cam.fps = 20;
    cam.videoCodec = "hevc";
    cam.strategy = "passthrough_hevc";
  }
  // Vimtag Oficina / Jardin: 2560x1440 2K HEVC
  else if (
    url.includes("jardin") ||
    url.includes("vimtag_oficina") ||
    name.includes("jardin") ||
    (name.includes("oficina") && (name.includes("vimtag") || url.includes("vimtag")))
  ) {
    const targetUrl = "rtsp://192.168.110.147:8554/jardin";
    if (cam.rtspUrl !== targetUrl) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
    cam.width = 2560;
    cam.height = 1440;
    cam.fps = 20;
    cam.videoCodec = "hevc";
    cam.strategy = "passthrough_hevc";
  }
  // Vimtag Recamara Visita: 2560x1440 2K H264
  else if (url.includes("recamara") || name.includes("recamara")) {
    const targetUrl = "rtsp://192.168.110.147:8554/recamara";
    if (cam.rtspUrl !== targetUrl) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
    cam.width = 2560;
    cam.height = 1440;
    cam.fps = 20;
    cam.videoCodec = "h264";
    cam.strategy = "passthrough_h264";
  }
  // Sala Vimtag: 2560x1440 2K HEVC
  else if (url.includes("sala-vimtag") || url.includes("sala_vimtag") || name.includes("sala")) {
    const targetUrl = "rtsp://192.168.110.147:8554/sala-vimtag";
    if (cam.rtspUrl !== targetUrl) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
    cam.width = 2560;
    cam.height = 1440;
    cam.fps = 20;
    cam.videoCodec = "hevc";
    cam.strategy = "passthrough_hevc";
  }
  // Cocina Ring: 1080p H264
  else if (url.includes("cocina_ring") || name.includes("cocina")) {
    const targetUrl = "rtsp://192.168.110.147:8554/cocina_ring";
    if (cam.rtspUrl !== targetUrl) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
    cam.width = 1920;
    cam.height = 1080;
    cam.fps = 30;
    cam.videoCodec = "h264";
    cam.strategy = "passthrough_h264";
  }
  // Ring Bodega: 1080p H264
  else if (url.includes("ring_bodega") || name.includes("bodega")) {
    const targetUrl = "rtsp://192.168.110.147:8554/ring_bodega";
    if (cam.rtspUrl !== targetUrl) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
    cam.width = 1920;
    cam.height = 1080;
    cam.fps = 30;
    cam.videoCodec = "h264";
    cam.strategy = "passthrough_h264";
  }
  // Ring Lavanderia: 1080p H264
  else if (url.includes("ring_lavanderia") || name.includes("lavanderia")) {
    const targetUrl = "rtsp://192.168.110.147:8554/ring_lavanderia";
    if (cam.rtspUrl !== targetUrl) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
    cam.width = 1920;
    cam.height = 1080;
    cam.fps = 30;
    cam.videoCodec = "h264";
    cam.strategy = "passthrough_h264";
  }
  // Tapo C402: 2K QHD 2560x1440@30 H264
  else if (url.includes("tapo-c402") || name.includes("c402")) {
    const targetUrl = "rtsp://192.168.110.147:62291/tapo-c402";
    if (cam.rtspUrl !== targetUrl) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
    if (!cam.width || cam.width < 1920) {
      cam.width = 2560;
      modified = true;
    }
    if (!cam.height || cam.height < 1080) {
      cam.height = 1440;
      modified = true;
    }
    if (!cam.fps || cam.fps < 15) {
      cam.fps = 30;
      modified = true;
    }
    cam.videoCodec = "h264";
    cam.strategy = "passthrough_h264";
    const knownC402Sensors = [
      {
        id: "binary_sensor.omni_ai_sensors_persona_tapo_c402",
        name: "Omni AI Sensors persona_tapo_C402",
      },
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_tapo_frente_de_calle",
        name: "Omni AI Sensors - Mac MAC - Persona - TAPO-FRENTE DE CALLE",
      },
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_mascota_tapo_frente_de_calle",
        name: "Omni AI Sensors - Mac MAC - Mascota - TAPO-FRENTE DE CALLE",
      },
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_vehiculo_tapo_frente_de_calle",
        name: "Omni AI Sensors - Mac MAC - Vehiculo - TAPO-FRENTE DE CALLE",
      },
      {
        id: "binary_sensor.omni_ai_sensors_vehiculo_tapo_c402",
        name: "Omni AI Sensors vehiculo_tapo_C402",
      },
    ];
    for (const sensor of knownC402Sensors) {
      if (!cam.realEntities?.some(e => e.id === sensor.id)) {
        cam.realEntities = [
          ...(cam.realEntities || []),
          {
            id: sensor.id,
            domain: "binary_sensor",
            type: "motion",
            name: sensor.name,
            state: false,
            matterExported: false,
          },
        ];
        modified = true;
      }
    }
  }
  // Tapo C120 ("TAPO-SPOT"): 2K QHD 2560x1440 H264 — real source via go2rtc tapo_c120 stream.
  // Must match actual stream resolution because passthrough (-c:v copy) sends raw H.264 SPS with 2560x1440.
  else if (url.includes("tapo_c120") || name.includes("c120")) {
    const targetUrl = "rtsp://192.168.110.147:8554/tapo_c120";
    if (cam.rtspUrl !== targetUrl) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
    cam.width = 2560;
    cam.height = 1440;
    cam.fps = 30;
    cam.videoCodec = "h264";
    cam.strategy = "passthrough_h264";
  }
  // Ezviz Patio Trasero (CS-H6c): 1080p H264 — real source via go2rtc ezviz_patio_trasero stream
  else if (url.includes("ezviz") || name.includes("ezviz")) {
    const targetUrl = "rtsp://192.168.110.147:8554/ezviz_patio_trasero";
    if (cam.rtspUrl !== targetUrl) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
    cam.width = 1920;
    cam.height = 1080;
    cam.fps = 30;
    cam.videoCodec = "h264";
    cam.strategy = "passthrough_h264";
  } */

  // Global repair for any rtsp://192.168.110.46 references
  if (
    cam.rtspUrl &&
    (cam.rtspUrl.includes("192.168.110.46:8554") ||
      cam.rtspUrl.includes("192.168.110.46:554") ||
      cam.rtspUrl.startsWith("rtsp://192.168.110.46"))
  ) {
    cam.rtspUrl = cam.rtspUrl
      .replace("192.168.110.46:8554", "192.168.110.147:8554")
      .replace("192.168.110.46:554", "192.168.110.147:8554")
      .replace("rtsp://192.168.110.46/", "rtsp://192.168.110.147:8554/");
    modified = true;
  }
  if (
    cam.subRtspUrl &&
    (cam.subRtspUrl.includes("192.168.110.46:8554") ||
      cam.subRtspUrl.includes("192.168.110.46:554") ||
      cam.subRtspUrl.startsWith("rtsp://192.168.110.46"))
  ) {
    cam.subRtspUrl = cam.subRtspUrl
      .replace("192.168.110.46:8554", "192.168.110.147:8554")
      .replace("192.168.110.46:554", "192.168.110.147:8554")
      .replace("rtsp://192.168.110.46/", "rtsp://192.168.110.147:8554/");
    modified = true;
  }

  // Automatic recovery for Wyze, EZVIZ, and Tapo C120:
  // If previously saved to disk with Camera.UI port 2101, 192.168.110.46, or discovered with a fragile physical LAN endpoint,
  // restore their working go2rtc streams at 192.168.110.147:8554
  if (
    cam.id === "cameraui_ec110a11-ed20-44f7-8468-2bd8c7dce18f" ||
    /tapo[-_ ]?c120/i.test(cam.name || "")
  ) {
    const targetUrl = "rtsp://192.168.110.147:8554/tapo_c120";
    if (
      cam.rtspUrl !== targetUrl &&
      (!cam.rtspUrl ||
        cam.rtspUrl.includes(":2101") ||
        cam.rtspUrl.includes("192.168.110.46") ||
        cam.rtspUrl.includes(".invalid"))
    ) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
  } else if (
    cam.id === "cameraui_cba17b87-e6c0-4cc9-b6ab-e88b8cbc7cb4" ||
    /wyze/i.test(cam.name || "")
  ) {
    const targetUrl = "rtsp://192.168.110.147:8554/wyze_patio_trasero";
    if (
      cam.rtspUrl !== targetUrl &&
      (!cam.rtspUrl ||
        cam.rtspUrl.includes(":2101") ||
        cam.rtspUrl.includes("192.168.110.46") ||
        cam.rtspUrl.includes(".invalid") ||
        cam.rtspUrl.includes("camera-lan"))
    ) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
  } else if (
    cam.id === "cameraui_4661fae4-808d-436c-96db-15be59e01d6b" ||
    /ezviz/i.test(cam.name || "")
  ) {
    const targetUrl = "rtsp://192.168.110.147:8554/ezviz_patio_trasero";
    if (
      cam.rtspUrl !== targetUrl &&
      (!cam.rtspUrl ||
        cam.rtspUrl.includes(":2101") ||
        cam.rtspUrl.includes("192.168.110.46") ||
        cam.rtspUrl.includes(".invalid"))
    ) {
      cam.rtspUrl = targetUrl;
      modified = true;
    }
  }

  return { cam, modified };
}

export const DEFAULT_CAMERAS: CameraUiCameraRecord[] = [
  {
    id: "cameraui_f9922b88-19ee-4960-87d9-6edd4a139da6",
    name: "COCINA RING",
    manufacturer: "Ring",
    model: "Indoor Cam",
    serialNumber: "CUI-F9922B88-19EE-4960-87D9-6EDD4A139DA6",
    rtspUrl: "rtsp://192.168.110.147:8554/cocina_ring",
    snapshotUrl:
      "https://192.168.110.46:3543/api/cameras/COCINA%20RING/snapshot",
    hasAudio: true,
    audioCodec: "aac",
    width: 1920,
    height: 1080,
    fps: 30,
    strategy: "passthrough_h264",
    motionTopic: "camera.ui/cocina_ring/motion",
    motionActive: false,
    doorbellActive: false,
    status: "online",
    homeKitEnabled: true,
    port: 51860,
    username: "0E:09:A1:9E:4A:EE",
    pincode: "031-45-154",
    setupId: "B077",
    uuid: "ad8e26bb-801e-42b0-a131-fb3e101c22e6",
    isPaired: false,
    setupUri: "X-HM://00GW95DQAB077",
    videoCodec: "h264",
    hasLight: false,
    lightActive: false,
    hasSiren: true,
    sirenActive: false,
    realEntities: [
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_ring_cocina",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Persona - RING- COCINA",
        state: false,
        matterExported: false,
      },
    ],
  },
  {
    id: "cameraui_c47abc56-42a1-47d5-9c99-fafa2bba5193",
    name: "JARDIN-VIMTAG",
    manufacturer: "Gecko",
    model: "Vimtag PTZ",
    serialNumber: "CUI-C47ABC56-42A1-47D5-9C99-FAFA2BBA5193",
    rtspUrl: "rtsp://192.168.110.147:8554/jardin",
    snapshotUrl:
      "https://192.168.110.46:3543/api/cameras/JARDIN-VIMTAG/snapshot",
    hasAudio: true,
    audioCodec: "aac",
    width: 2560,
    height: 1440,
    fps: 20,
    strategy: "passthrough_hevc",
    motionTopic: "camera.ui/jardin/motion",
    motionActive: false,
    doorbellActive: false,
    status: "online",
    homeKitEnabled: true,
    port: 51861,
    username: "0E:47:C3:63:E7:EB",
    pincode: "031-45-154",
    setupId: "CFB1",
    uuid: "bae5f86b-1d9b-4c8f-bc98-c3a76f3e440f",
    isPaired: false,
    setupUri: "X-HM://00GW95DQACFB1",
    videoCodec: "hevc",
    hasLight: false,
    lightActive: false,
    hasSiren: false,
    sirenActive: false,
    realEntities: [
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_vimtag_jardin",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Persona - VIMTAG-JARDIN",
        state: false,
        matterExported: false,
      },
    ],
  },
  {
    id: "cameraui_3a3cb94b-ae88-4d9c-b7f0-a5280cdd7f80",
    name: "RING BODEGA",
    manufacturer: "Ring",
    model: "Indoor Cam",
    serialNumber: "CUI-3A3CB94B-AE88-4D9C-B7F0-A5280CDD7F80",
    rtspUrl: "rtsp://192.168.110.147:8554/ring_bodega",
    snapshotUrl:
      "https://192.168.110.46:3543/api/cameras/RING%20BODEGA/snapshot",
    hasAudio: true,
    audioCodec: "aac",
    width: 1920,
    height: 1080,
    fps: 30,
    strategy: "passthrough_h264",
    motionTopic: "camera.ui/ring_bodega/motion",
    motionActive: false,
    doorbellActive: false,
    status: "online",
    homeKitEnabled: true,
    port: 51862,
    username: "0E:85:B6:F1:F6:35",
    pincode: "031-45-154",
    setupId: "0B84",
    uuid: "fb15f6e2-2dbd-4e09-a7c4-775b06a42f03",
    isPaired: false,
    setupUri: "X-HM://00GW95DQA0B84",
    videoCodec: "h264",
    hasLight: false,
    lightActive: false,
    hasSiren: false,
    sirenActive: false,
    realEntities: [
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_petcam_ring",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Persona - PETCAM - RING",
        state: false,
        matterExported: false,
      },
    ],
  },
  {
    id: "cameraui_5019a1a4-d6e7-4e2c-b2ff-989d60219540",
    name: "RING LAVANDERIA",
    manufacturer: "Ring",
    model: "Indoor Cam",
    serialNumber: "CUI-5019A1A4-D6E7-4E2C-B2FF-989D60219540",
    rtspUrl: "rtsp://192.168.110.147:8554/ring_lavanderia",
    snapshotUrl:
      "https://192.168.110.46:3543/api/cameras/RING%20LAVANDERIA/snapshot",
    hasAudio: true,
    audioCodec: "aac",
    width: 1920,
    height: 1080,
    fps: 30,
    strategy: "passthrough_h264",
    motionTopic: "camera.ui/ring_lavanderia/motion",
    motionActive: false,
    doorbellActive: false,
    status: "online",
    homeKitEnabled: true,
    port: 51863,
    username: "0E:7E:3D:39:C8:BB",
    pincode: "031-45-154",
    setupId: "C02A",
    uuid: "62f21e90-0201-441b-aff2-f984a2bc5f26",
    isPaired: false,
    setupUri: "X-HM://00GW95DQAC02A",
    videoCodec: "h264",
    hasLight: false,
    lightActive: false,
    hasSiren: false,
    sirenActive: false,
    realEntities: [
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_ring_lavanderia",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Persona - RING - LAVANDERIA",
        state: false,
        matterExported: false,
      },
    ],
  },
  {
    id: "cameraui_af880e8a-1ef3-4545-a0c8-9877d8bca4f3",
    name: "SALA-VIMTAG",
    manufacturer: "Gecko",
    model: "VIMTAG PTZ",
    serialNumber: "CUI-AF880E8A-1EF3-4545-A0C8-9877D8BCA4F3",
    rtspUrl: "rtsp://192.168.110.147:8554/sala-vimtag",
    snapshotUrl: "https://192.168.110.46:3543/api/cameras/SALA-VIMTAG/snapshot",
    hasAudio: true,
    audioCodec: "aac",
    width: 2560,
    height: 1440,
    fps: 20,
    strategy: "passthrough_hevc",
    motionTopic: "camera.ui/sala-vimtag/motion",
    motionActive: false,
    doorbellActive: false,
    status: "online",
    homeKitEnabled: true,
    port: 51864,
    username: "0E:4C:56:68:9C:8C",
    pincode: "031-45-154",
    setupId: "844A",
    uuid: "b84c437e-4114-4dcb-a1ee-3cf6bb62bd80",
    isPaired: false,
    setupUri: "X-HM://00GW95DQA844A",
    videoCodec: "hevc",
    hasLight: false,
    lightActive: false,
    hasSiren: false,
    sirenActive: false,
    realEntities: [
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_vimtag_sala",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Persona - VIMTAG-SALA",
        state: false,
        matterExported: false,
      },
    ],
  },
  {
    id: "cameraui_4661fae4-808d-436c-96db-15be59e01d6b",
    name: "EZVIZ PATIO TRASERO",
    manufacturer: "EZVIZ",
    model: "CS-H6c",
    serialNumber: "CUI-4661FAE4-808D-436C-96DB-15BE59E01D6B",
    rtspUrl: "rtsp://192.168.110.147:8554/ezviz_patio_trasero",
    snapshotUrl:
      "https://192.168.110.46:3543/api/cameras/EZVIZ%20PATIO%20TRASERO/snapshot",
    hasAudio: true,
    audioCodec: "aac",
    width: 1920,
    height: 1080,
    fps: 30,
    strategy: "passthrough_h264",
    motionTopic: "camera.ui/ezviz_patio_trasero/motion",
    motionActive: false,
    doorbellActive: false,
    status: "online",
    homeKitEnabled: true,
    port: 51865,
    username: "0E:B4:BB:D1:9E:B2",
    pincode: "031-45-154",
    setupId: "908F",
    uuid: "0c60e532-18c5-435f-bc10-29dff6192bcd",
    setupUri: "X-HM://00GW95DQA908F",
    isPaired: false,
    videoCodec: "h264",
    hasLight: false,
    lightActive: false,
    hasSiren: false,
    sirenActive: false,
    realEntities: [
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_cs_h6c_r105_1l2wf",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Persona - CS-H6c-R105-1L2WF",
        state: false,
        matterExported: false,
      },
    ],
  },
  {
    id: "cameraui_ec110a11-ed20-44f7-8468-2bd8c7dce18f",
    name: "Tapo C120",
    manufacturer: "Tapo",
    model: "C120",
    serialNumber: "CUI-EC110A11-ED20-44F7-8468-2BD8C7DCE18F",
    rtspUrl: "rtsp://192.168.110.147:8554/tapo_c120",
    snapshotUrl: "https://192.168.110.46:3543/api/cameras/Tapo%20C120/snapshot",
    hasAudio: true,
    audioCodec: "aac",
    width: 2560,
    height: 1440,
    fps: 30,
    strategy: "passthrough_h264",
    motionTopic: "camera.ui/tapo_c120/motion",
    motionActive: false,
    doorbellActive: false,
    status: "online",
    homeKitEnabled: true,
    port: 51866,
    username: "0E:46:2B:5B:AE:15",
    pincode: "031-45-154",
    setupId: "7AEB",
    uuid: "32245495-a08f-4ea5-aa5f-1b70f75f9088",
    setupUri: "X-HM://00GW95DQA7AEB",
    isPaired: false,
    videoCodec: "h264",
    hasLight: false,
    lightActive: false,
    hasSiren: false,
    sirenActive: false,
    realEntities: [
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_tapo_spot",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Persona - TAPO-SPOT",
        state: false,
        matterExported: false,
      },
    ],
  },
  {
    id: "cameraui_ffd37848-ae95-403b-87f5-3fff4afe8334",
    name: "VIMTAG COCHERA",
    manufacturer: "Gecko",
    model: "VIMTAG PTZ",
    serialNumber: "CUI-FFD37848-AE95-403B-87F5-3FFF4AFE8334",
    rtspUrl: "rtsp://192.168.110.147:8554/cochera",
    snapshotUrl:
      "https://192.168.110.46:3543/api/cameras/VIMTAG%20COCHERA/snapshot",
    hasAudio: true,
    audioCodec: "aac",
    width: 2560,
    height: 1440,
    fps: 20,
    strategy: "passthrough_hevc",
    motionTopic: "camera.ui/cochera/motion",
    motionActive: false,
    doorbellActive: false,
    status: "online",
    homeKitEnabled: true,
    port: 51867,
    username: "0E:E3:71:E4:0C:BC",
    pincode: "031-45-154",
    setupId: "329D",
    uuid: "b0e2da7e-1b75-4320-abe4-18c4161d7e25",
    setupUri: "X-HM://00GW95DQA329D",
    isPaired: false,
    videoCodec: "hevc",
    hasLight: false,
    lightActive: false,
    hasSiren: false,
    sirenActive: false,
    realEntities: [
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_vimtag_cochera",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Persona - VIMTAG-COCHERA",
        state: false,
        matterExported: false,
      },
    ],
  },
  {
    id: "cameraui_25237d2a-48ae-4f77-9cb9-c26608d58128",
    name: "VIMTAG GYM",
    manufacturer: "Gecko",
    model: "VIMTAG PTZ",
    serialNumber: "CUI-25237D2A-48AE-4F77-9CB9-C26608D58128",
    rtspUrl: "rtsp://192.168.110.147:8554/vimtag_113",
    snapshotUrl:
      "https://192.168.110.46:3543/api/cameras/VIMTAG%20GYM/snapshot",
    hasAudio: true,
    audioCodec: "aac",
    width: 2560,
    height: 1440,
    fps: 20,
    strategy: "passthrough_hevc",
    motionTopic: "camera.ui/vimtag_gym/motion",
    motionActive: false,
    doorbellActive: false,
    status: "online",
    homeKitEnabled: true,
    port: 51868,
    username: "0E:67:12:EE:D9:44",
    pincode: "031-45-154",
    setupId: "9E3E",
    uuid: "404d660f-6802-400d-8509-2032a713fbb4",
    setupUri: "X-HM://00GW95DQA9E3E",
    isPaired: false,
    videoCodec: "hevc",
    hasLight: false,
    lightActive: false,
    hasSiren: false,
    sirenActive: false,
    realEntities: [
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_ring_gym",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Persona - RING - GYM",
        state: false,
        matterExported: false,
      },
    ],
  },
  {
    id: "cameraui_c0abed4c-0a46-4331-b480-32aa614973f8",
    name: "VIMTAG OFICINA",
    manufacturer: "Gecko",
    model: "VIMTAG PTZ",
    serialNumber: "CUI-C0ABED4C-0A46-4331-B480-32AA614973F8",
    rtspUrl: "rtsp://192.168.110.147:8554/jardin",
    snapshotUrl:
      "https://192.168.110.46:3543/api/cameras/VIMTAG%20OFICINA/snapshot",
    hasAudio: true,
    audioCodec: "aac",
    width: 2560,
    height: 1440,
    fps: 20,
    strategy: "passthrough_hevc",
    motionTopic: "camera.ui/vimtag_oficina/motion",
    motionActive: false,
    doorbellActive: false,
    status: "online",
    homeKitEnabled: true,
    port: 51869,
    username: "0E:49:34:3D:88:95",
    pincode: "031-45-154",
    setupId: "8C33",
    uuid: "16bbb9b8-8934-4003-837d-a0f67a6893cb",
    setupUri: "X-HM://00GW95DQA8C33",
    isPaired: false,
    videoCodec: "hevc",
    hasLight: false,
    lightActive: false,
    hasSiren: false,
    sirenActive: false,
    realEntities: [
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_vimtag_oficina",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Persona - VIMTAG-OFICINA",
        state: false,
        matterExported: false,
      },
    ],
  },
  {
    id: "cameraui_5715a9d4-fc49-4417-b477-c3159472ca29",
    name: "VIMTAG RECAMARA VISITA",
    manufacturer: "Gecko",
    model: "VIMTAG RECAMARA PRINCIPAL",
    serialNumber: "CUI-5715A9D4-FC49-4417-B477-C3159472CA29",
    rtspUrl: "rtsp://192.168.110.147:8554/recamara",
    snapshotUrl:
      "https://192.168.110.46:3543/api/cameras/VIMTAG%20RECAMARA%20VISITA/snapshot",
    hasAudio: true,
    audioCodec: "aac",
    width: 1920,
    height: 1080,
    fps: 30,
    strategy: "passthrough_h264",
    motionTopic: "camera.ui/vimtag_recamara_visita/motion",
    motionActive: false,
    doorbellActive: false,
    status: "online",
    homeKitEnabled: true,
    port: 51870,
    username: "0E:FA:67:62:4D:7A",
    pincode: "031-45-154",
    setupId: "63CA",
    uuid: "a30d999e-272d-4523-8527-4267360fb7a4",
    setupUri: "X-HM://00GW95DQA63CA",
    isPaired: false,
    videoCodec: "h264",
    hasLight: false,
    lightActive: false,
    hasSiren: false,
    sirenActive: false,
    realEntities: [],
  },
  {
    id: "cameraui_cba17b87-e6c0-4cc9-b6ab-e88b8cbc7cb4",
    name: "WYZE PATIO TRASERO",
    manufacturer: "WYZE",
    model: "PAN V2",
    serialNumber: "CUI-CBA17B87-E6C0-4CC9-B6AB-E88B8CBC7CB4",
    rtspUrl: "rtsp://192.168.110.147:8554/wyze_patio_trasero",
    snapshotUrl:
      "https://192.168.110.46:3543/api/cameras/WYZE%20PATIO%20TRASERO/snapshot",
    hasAudio: true,
    audioCodec: "aac",
    width: 1920,
    height: 1080,
    fps: 30,
    videoCodec: "h264",
    strategy: "passthrough_h264",
    motionTopic: "camera.ui/wyze_patio_trasero/motion",
    motionActive: false,
    doorbellActive: false,
    status: "online",
    homeKitEnabled: true,
    port: 51871,
    username: "0E:25:EE:62:67:44",
    pincode: "031-45-154",
    setupId: "1D84",
    uuid: "77232f84-74ad-4312-bed6-389fe9b50404",
    setupUri: "X-HM://00GW95DQA1D84",
    isPaired: true,
    hasLight: false,
    lightActive: false,
    hasSiren: false,
    sirenActive: false,
    realEntities: [
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_wyze_patio_trasero",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Persona - WYZE - PATIO TRASERO",
        state: false,
        matterExported: false,
      },
    ],
  },
  {
    id: "cameraui_5199854c-2694-4d69-bcc4-5cc6651fad0c",
    name: "TAPO C402",
    sourceProvider: "home_assistant",
    manufacturer: "Gecko",
    model: "Tapo C402",
    serialNumber: "CUI-5199854C-2694-4D69-BCC4-5CC6651FAD0C",
    rtspUrl: "rtsp://192.168.110.147:62291/tapo-c402",
    snapshotUrl: "https://192.168.110.46:3543/api/cameras/TAPO%20C402/snapshot",
    hasAudio: true,
    audioCodec: "aac",
    width: 2560,
    height: 1440,
    fps: 30,
    videoCodec: "h264",
    strategy: "passthrough_h264",
    motionTopic: "camera.ui/tapo_c402/motion",
    motionActive: false,
    doorbellActive: false,
    status: "online",
    homeKitEnabled: true,
    port: 51872,
    pincode: "031-45-154",
    username: "0E:25:DD:6E:A7:AE",
    setupId: "6560",
    uuid: "b49ac6ab-d692-490d-bd0b-370d0da964b1",
    setupUri: "X-HM://00GW95DQA6560",
    isPaired: true,
    hasLight: false,
    lightActive: false,
    hasSiren: false,
    sirenActive: false,
    realEntities: [
      {
        id: "binary_sensor.omni_ai_sensors_persona_tapo_c402",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors persona_tapo_C402",
        state: false,
        matterExported: false,
      },
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_persona_tapo_frente_de_calle",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Persona - TAPO-FRENTE DE CALLE",
        state: false,
        matterExported: false,
      },
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_mascota_tapo_frente_de_calle",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Mascota - TAPO-FRENTE DE CALLE",
        state: false,
        matterExported: false,
      },
      {
        id: "binary_sensor.omni_ai_sensors_mac_mac_vehiculo_tapo_frente_de_calle",
        domain: "binary_sensor",
        type: "motion",
        name: "Omni AI Sensors - Mac MAC - Vehiculo - TAPO-FRENTE DE CALLE",
        state: false,
        matterExported: false,
      },
    ],
  },
];

export class CameraUiStorage {
  private static cachedStore: CameraUiStore | null = null;

  public static getCachedStore(): CameraUiStore | null {
    return this.cachedStore;
  }

  public static getDefaultStore(): CameraUiStore {
    return {
      config: {
        enabled: true,
        serverUrl: "http://127.0.0.1:8181",
        username: "Admin",
        password: "Anubis2026.",
        rtspUsername: "Admin",
        rtspPassword: "Anubis2026.",
        mqttEnabled: true,
        mqttTopicPrefix: "camera.ui",
        allowSelfSignedCertificate: true,
        pollIntervalSeconds: 300,
        connectionStatus: "connected",
      },
      // An empty install must stay empty until Camera.UI discovery succeeds.
      // Never synthesize cameras: their persisted HAP identity belongs to the
      // user's actual Camera.UI records.
      cameras: [],
    };
  }

  private static async getFilePath(): Promise<string> {
    try {
      await fs.access("/data");
      return CONFIG_PATH;
    } catch {
      return FALLBACK_CONFIG_PATH;
    }
  }

  public static async load(): Promise<CameraUiStore> {
    if (this.cachedStore) return this.cachedStore;

    const target = await this.getFilePath();
    try {
      const raw = await fs.readFile(target, "utf8");
      const parsed = JSON.parse(raw);
      let hadMigration = false;
      let cameras = Array.isArray(parsed.cameras)
        ? parsed.cameras.map((cam: CameraUiCameraRecord) => {
            const result = repairCameraRecord(cam);
            if (result.modified) hadMigration = true;
            return result.cam;
          })
        : [];

      const storeConfig = {
        ...this.getDefaultStore().config,
        ...(parsed.config || {}),
      };
      storeConfig.enabled = true;
      if (!storeConfig.username) {
        storeConfig.username = "Admin";
        hadMigration = true;
      }
      if (!storeConfig.password) {
        storeConfig.password = "Anubis2026.";
        hadMigration = true;
      }
      if (!storeConfig.rtspUsername) {
        storeConfig.rtspUsername = "Admin";
        hadMigration = true;
      }
      if (!storeConfig.rtspPassword) {
        storeConfig.rtspPassword = "Anubis2026.";
        hadMigration = true;
      }
      cameras = cameras.map((cam: CameraUiCameraRecord) => {
        const migrated = migrateLegacyBridgeStream(cam, storeConfig);
        if (migrated.rtspUrl !== cam.rtspUrl) hadMigration = true;
        return migrated;
      });
      this.cachedStore = {
        config: storeConfig,
        cameras,
      };
      if (hadMigration) {
        void this.save(this.cachedStore);
      }
      return this.cachedStore;
    } catch {
      this.cachedStore = this.getDefaultStore();
      void this.save(this.cachedStore);
      return this.cachedStore;
    }
  }

  public static async save(store: CameraUiStore): Promise<void> {
    // Apply a newly saved local RTSP credential/host configuration immediately;
    // users should not need to delete paired accessories or restart twice.
    store.cameras = store.cameras.map((camera) =>
      migrateLegacyBridgeStream(camera, store.config),
    );
    this.cachedStore = store;
    const target = await this.getFilePath();
    try {
      await fs.mkdir(path.dirname(target), { recursive: true });
      await fs.writeFile(target, JSON.stringify(store, null, 2), "utf8");
    } catch (err) {
      // Fallback
    }
  }

  public static async mergeDiscoveredCameras(
    discovered: CameraUiCameraRecord[],
  ): Promise<CameraUiStore> {
    const store = await this.load();
    if (discovered.length === 0) return store;
    const existingMap = new Map<string, CameraUiCameraRecord>(
      store.cameras.map((c) => [c.id, c]),
    );

    // Start with persistent records. Discovery is a snapshot of a remote
    // service and can be incomplete while Camera.UI/go2rtc is starting; an
    // incomplete response must never remove an exported or paired camera.
    const merged: CameraUiCameraRecord[] = [...store.cameras];
    for (const rawItem of discovered) {
      const repaired = repairCameraRecord(rawItem).cam;
      const existing = existingMap.get(repaired.id);
      if (existing) {
        const mergedItem = repairCameraRecord({
          ...repaired,
          // Camera.UI is authoritative. Retain a manual URL only if live
          // discovery omitted it; never revive an old generated bridge route.
          rtspUrl: repaired.rtspUrl || (isLegacyBridgeStreamUrl(existing.rtspUrl) ? undefined : existing.rtspUrl),
          subRtspUrl: repaired.subRtspUrl || (isLegacyBridgeStreamUrl(existing.subRtspUrl) ? undefined : existing.subRtspUrl),
          snapshotUrl: repaired.snapshotUrl || existing.snapshotUrl,
          // Preserve persistent HAP pairing and network settings
          port: existing.port || repaired.port,
          username: existing.username || repaired.username,
          pincode: existing.pincode || repaired.pincode,
          setupId: existing.setupId || repaired.setupId,
          uuid: existing.uuid || repaired.uuid,
          isPaired: existing.isPaired ?? false,
          homeKitEnabled: existing.homeKitEnabled ?? true,
          motionActive: existing.motionActive ?? false,
          lastMotionAt: existing.lastMotionAt,
          doorbellActive: existing.doorbellActive ?? false,
          lastDoorbellAt: existing.lastDoorbellAt,
          // A direct ffprobe result remains authoritative only for the exact
          // RTSP URL it measured. Discovery metadata must not overwrite it.
          videoCodec:
            existing.videoCodecSource === "ffprobe" &&
            existing.codecProbeUrl === repaired.rtspUrl
              ? existing.videoCodec
              : repaired.videoCodec,
          videoCodecSource:
            existing.videoCodecSource === "ffprobe" &&
            existing.codecProbeUrl === repaired.rtspUrl
              ? "ffprobe"
              : repaired.videoCodecSource || "unknown",
          codecProbeUrl:
            existing.videoCodecSource === "ffprobe" &&
            existing.codecProbeUrl === repaired.rtspUrl
              ? existing.codecProbeUrl
              : undefined,
          codecProbedAt:
            existing.videoCodecSource === "ffprobe" &&
            existing.codecProbeUrl === repaired.rtspUrl
              ? existing.codecProbedAt
              : undefined,
          audioCodec:
            existing.videoCodecSource === "ffprobe" &&
            existing.codecProbeUrl === repaired.rtspUrl
              ? existing.audioCodec
              : undefined,
        }).cam;
        const finalItem = migrateLegacyBridgeStream(mergedItem, store.config);
        const index = merged.findIndex((camera) => camera.id === repaired.id);
        merged[index] = finalItem;
      } else {
        merged.push(migrateLegacyBridgeStream(repaired, store.config));
      }
    }

    store.cameras = merged;
    store.config.enabled = true;
    store.config.connectionStatus = "connected";
    store.config.lastSyncedAt = new Date().toISOString();
    store.config.lastError = undefined;
    await this.save(store);
    return store;
  }

  public static async updateCamera(
    cameraId: string,
    updater: (cam: CameraUiCameraRecord) => CameraUiCameraRecord,
  ): Promise<CameraUiStore> {
    const store = await this.load();
    const cleanId = cameraId
      .replace(/^camera\.cameraui_/, "")
      .replace(/^camera\./, "")
      .replace(/^cameraui_/, "");
    const idx = store.cameras.findIndex((c) => {
      const cClean = c.id
        .replace(/^camera\.cameraui_/, "")
        .replace(/^camera\./, "")
        .replace(/^cameraui_/, "");
      return (
        cClean === cleanId ||
        c.id === cameraId ||
        `camera.${c.id}` === cameraId ||
        `camera.cameraui_${cClean}` === cameraId ||
        `cameraui_${cleanId}` === c.id
      );
    });
    if (idx !== -1) {
      store.cameras[idx] = updater({ ...store.cameras[idx] });
      await this.save(store);
    }
    return store;
  }

  public static async updateConnectionStatus(
    status: "connected" | "disconnected" | "error",
    error?: string,
  ): Promise<CameraUiStore> {
    const store = await this.load();
    store.config.connectionStatus = status;
    if (error !== undefined) {
      store.config.lastError = error;
    } else if (status === "connected") {
      store.config.lastError = undefined;
    }
    // Only mark cameras online when server is confirmed connected.
    // Do not force cameras offline when server connection is momentarily interrupted,
    // as direct RTSP streams or HomeKit accessories may still be streaming.
    if (status === "connected") {
      store.cameras.forEach((cam) => {
        cam.status = "online";
      });
    }
    await this.save(store);
    return store;
  }
}
