import type { HassState } from "../utils/ha-state.js";
import type {
  CameraCapabilitiesInfo,
  ResolvedStreamSource,
  StreamSourceType,
  VideoCodecType,
  AudioCodecType,
  StreamStrategy,
} from "./camera-types.js";
import {
  type ProbeResult,
  resolveFfmpegPath,
} from "./homekit/ffmpeg-helper.js";

/**
 * Detects real camera capabilities and determines the optimal streaming strategy.
 *
 * Rules:
 * - H.264 streams use passthrough / remux copy mode (no transcoding).
 * - Compatible audio (AAC-LC, AAC-ELD, Opus, PCM) is forwarded; incompatible audio is omitted (video-only).
 * - H.265 or MJPEG streams are flagged as requiring transcoding.
 * - Unknown or invalid stream sources are marked as unsupported.
 */
export function detectCameraCapabilities(
  state: HassState,
  resolvedSource?: ResolvedStreamSource,
  probeResult?: ProbeResult,
): CameraCapabilitiesInfo {
  const attrs = state.attributes || {};
  const isAvailable =
    state.state !== "unavailable" && state.state !== "unknown";

  // Determine Source Protocol
  let streamSourceType: StreamSourceType = "unknown";
  if (resolvedSource?.sourceType) {
    streamSourceType = resolvedSource.sourceType;
  } else if (attrs.frontend_stream_type === "webrtc") {
    streamSourceType = "webrtc";
  } else if (attrs.frontend_stream_type === "hls") {
    streamSourceType = "hls";
  } else if (
    typeof attrs.stream_source === "string" &&
    attrs.stream_source.startsWith("rtsp")
  ) {
    streamSourceType = "rtsp";
  }

  // Detect Video Codec (prefer probe result if valid)
  let videoCodec: VideoCodecType = "h264";
  if (probeResult?.videoCodec) {
    const pCode = probeResult.videoCodec.toLowerCase();
    if (pCode.includes("265") || pCode.includes("hevc")) {
      videoCodec = "h265";
    } else if (pCode.includes("mjpeg") || pCode.includes("jpeg")) {
      videoCodec = "mjpeg";
    } else if (pCode.includes("264") || pCode.includes("avc")) {
      videoCodec = "h264";
    }
  } else {
    const rawVideoCodec = (attrs.video_codec || "").toLowerCase();
    if (rawVideoCodec.includes("265") || rawVideoCodec.includes("hevc")) {
      videoCodec = "h265";
    } else if (
      rawVideoCodec.includes("mjpeg") ||
      rawVideoCodec.includes("jpeg")
    ) {
      videoCodec = "mjpeg";
    } else if (rawVideoCodec.includes("264") || rawVideoCodec.includes("avc")) {
      videoCodec = "h264";
    }
  }

  // Detect Audio Codec
  let audioCodec: AudioCodecType = "none";
  let hasAudio = false;

  if (probeResult) {
    hasAudio = probeResult.hasAudio;
    if (probeResult.audioCodec) {
      const pAudio = probeResult.audioCodec.toLowerCase();
      if (pAudio.includes("aac") || pAudio.includes("mp4a")) {
        audioCodec = "aac_lc";
      } else if (pAudio.includes("opus")) {
        audioCodec = "opus";
      } else if (
        pAudio.includes("pcm") ||
        pAudio.includes("alaw") ||
        pAudio.includes("ulaw")
      ) {
        audioCodec = "pcm";
      } else {
        audioCodec = "incompatible";
        hasAudio = false;
      }
    }
  } else {
    const rawAudioCodec = (attrs.audio_codec || "").toLowerCase();
    hasAudio = attrs.has_audio !== false && rawAudioCodec !== "none";
    if (hasAudio) {
      if (rawAudioCodec.includes("aac") || rawAudioCodec.includes("mp4a")) {
        audioCodec = "aac_lc";
      } else if (rawAudioCodec.includes("opus")) {
        audioCodec = "opus";
      } else if (
        rawAudioCodec.includes("pcm") ||
        rawAudioCodec.includes("alaw") ||
        rawAudioCodec.includes("ulaw")
      ) {
        audioCodec = "pcm";
      } else if (rawAudioCodec) {
        audioCodec = "incompatible";
        hasAudio = false;
      } else {
        audioCodec = "aac_lc";
      }
    }
  }

  // Determine Dimensions & FPS
  const width =
    probeResult?.width || Number(attrs.video_width || attrs.width || 1920);
  const height =
    probeResult?.height || Number(attrs.video_height || attrs.height || 1080);
  const maxFps =
    probeResult?.fps || Number(attrs.fps || attrs.frame_rate || 30);

  // Strategy Determination
  let strategy: StreamStrategy = "unsupported";
  let requiresTranscoding = false;
  let transcodingReason: string | undefined;

  const hasStreamSource = resolvedSource
    ? Boolean(resolvedSource.url) || resolvedSource.sourceType === "webrtc"
    : streamSourceType !== "unknown" || state.state === "streaming";
  const hasLiveStream = hasStreamSource && isAvailable;

  if (!hasLiveStream) {
    strategy = "unsupported";
    transcodingReason =
      "Live View no disponible: Home Assistant no expone una fuente reproducible.";
    // camera_proxy_stream is an HTTP multipart/JPEG representation generated by
    // Home Assistant.  Camera attributes may say H.264, but copying that proxy
    // response as H.264 produces an invalid RTP stream for Apple Home.
  } else if (
    videoCodec === "h264" &&
    resolvedSource?.sourceType !== "ha_proxy"
  ) {
    if (hasAudio && audioCodec !== "incompatible" && audioCodec !== "none") {
      strategy = "passthrough_h264";
    } else {
      strategy = "passthrough_video_only";
    }
  } else {
    strategy = "transcode_required";
    requiresTranscoding = true;
    transcodingReason = `Video codec is ${videoCodec} and requires ultra-low-latency H.264 transcoding.`;
  }

  return {
    hasLiveStream,
    streamSourceType,
    videoCodec,
    audioCodec,
    hasAudio,
    resolution: { width, height },
    maxFps,
    strategy,
    requiresTranscoding,
    transcodingReason,
    snapshotSupported: true,
    hksvCapable: hasLiveStream && Boolean(resolveFfmpegPath()),
    snapshotUrl:
      resolvedSource?.snapshotUrl || `/api/camera_proxy/${state.entity_id}`,
  };
}
