name: "Matter All-in-One chrisalvir"
description: "All-in-one bridge and custom UI for Home Assistant entities exported to Apple Home, Google Home, SmartThings and Alexa over Matter"
version: "1.4.12"
slug: "matter_all_in_one_bridge"
image: "ghcr.io/chrisalvir1/matter-all-in-one-chrisalvir"
init: false
host_network: true
ingress: true
ingress_port: 8283
arch:
  - amd64
  - aarch64
hassio_api: true
homeassistant_api: true
hassio_role: homeassistant
options:
  ipv4_only: true
schema:
  host: str?
  token: str?
  group_by_device_id: bool?
  mdnsinterface: str?
  ipv4_only: bool?
