name: "Matter All-in-One Bridge"
description: "Expose Home Assistant entities through one stable Matter bridge with HomeKit-compatible mappings."
version: "1.2.50"
slug: "matter_all_in_one_bridge"
image: "ghcr.io/chrisalvir1/matter-all-in-one-chrisalvir"
init: false
host_network: true
ingress: true
ingress_port: 8283
arch:
  - amd64
  - aarch64
hassio_api: true
homeassistant_api: true
hassio_role: homeassistant
options: {}
schema:
  host: str?
  token: str?
  group_by_device_id: bool?
  mdnsinterface: str?
  ipv4_only: bool?
